name: "sam2ooh2"
listen: "0.0.0.0:80"
env: "dev"

sqlite:
  host: "localhost"
  user: "sqlite"
  port: 5432
  password: "1q2w3e4r!"
  dbName: "samsamoohooh"
  options:
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: "30m"